services:
  strapi:
    build:
      context: .
      dockerfile: dockerfile.strapi
    ports:
      - "1337:1337"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development